### ISSUE TITLE
Sape!!!!

### ISSUE THREAD

**Issue by SebastianR3** [AlexOrdaya/AlexOrdaya.github.io#1]
### Probando los issues.Alberto PTO.

Agrega el año de 2021

**Comment by AlexOrdaya** [comment]
hahah NO señor usted necesita hacer cambio en PTO (no se si hace referencia a pito o puto por favor definir HAHA)
Reject!

**Comment by SebastianR3** [comment]
Hahaha Me hiciste pensar que puse Alberto xD

**Comment by AlexOrdaya** [comment]
AJAJAJ is true!, correjido tema cerrado.
